version: '3.8'

services:
  app:
    build: .
    container_name: db_app
    volumes:
      - ./db_app:/app
    environment:
      - name=value
    ports:
      - "3000:3000"
    networks:
      - my_network

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - my_network
  
volumes:
  db:
    driver: local

networks:
  my_network:
    driver: bridge
